### ISSUE TITLE
Add support for using Shimly within CJS bundle

### ISSUE THREAD

**Issue by munkychop** [nicbell/shimly#1]
Currently, it seems as though Shimly has to be loaded as a standalone script file, or as part of an Uglify bundle, because [at least some of] the shims break when bundled using CJS-style closures.

I encountered this problem today with Element.classList, due to the shim using the 'self' keyword, which was showing up as undefined in the Browserify closure. And of course I only noticed this on a browser that needed the shim (IE9 in this case).

This feature could be implemented by slightly modifying some of the shims so that they use specific globally available objects that are explicitly defined by Shimly within a 'ShimlyGlobals' object, or something similar.

**Comment by nicbell** [comment]
I'll try look into a solution where I don't have to modify the shims as that may be a headache to maintain every time they are updated.

**Comment by munkychop** [comment]
Ok cool, yep – wrapping each of them in a closure and passing in parameters to replace references that are expected to be global could work.

**Comment by munkychop** [comment]
This is actually NOT an issue and the problem I was experiencing was due to an implementation error in my application.

**Comment by mrmartineau** [comment]
:tongue:
